### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [ashif-ismail/PocketPrep-Android#1]
it shoes this error..
06-16 13:31:37.230 14753-14753/me.ashif.pocketprep E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ashif.pocketprep/me.ashif.pocketprep.QuestionsActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
                                                                         at android.app.ActivityThread.access$700(ActivityThread.java:159)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:176)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:525)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                         at java.util.ArrayList.get(ArrayList.java:308)
                                                                         at me.ashif.pocketprep.Exam.getNextQuestion(Exam.java:43)
                                                                         at me.ashif.pocketprep.QuestionsActivity.onCreate(QuestionsActivity.java:24)
                                                                         at android.app.Activity.performCreate(Activity.java:5372)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349) 
                                                                         at android.app.ActivityThread.access$700(ActivityThread.java:159) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                         at android.os.Looper.loop(Looper.java:176) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5419) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) 
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by ashif-ismail** [comment]
@sreemanrao 
Could you please specify more information regarding this issue?When does the exception occur?
Meanwhile you could follow up this[https://goo.gl/a3MtMH] to know more about the specified exception

**Comment by ghost** [comment]
if i click on mock test button in the starting activity its giving the above error

**Comment by ashif-ismail** [comment]
Its working Perfectly,check this GIF [https://imgflip.com/gif/15xfch](url),Check the previous link that i have shared to understand the problem.Let me know the results
Make sure that your during your initial run of the app,you have internet activated.As the questions are stored on Parse cloud DB.It first needs to be connected with the DB to populate the Questions List in the App,I think this may be the reason for showing IndexOutOfBoundException

**Comment by ghost** [comment]
it isnt working :(
how to connect to the parser DB?

**Comment by ashif-ismail** [comment]
You don't have to do anything to connect to Parse cloud, it's already configured in the code
The problem may be arising when the app fails to connect to the DB to populate the questions.I don't think this can be rectified because Parse has permanently terminated their service few months back.
The option you have  now is to migrate to another mBAAS service like backendless or firebase 
Or you could also use a local SQLite DB

Hope ,everything is clear
